# Generated by Django 4.2.4 on 2024-03-05 07:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0007_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fin_CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_billing_address', models.CharField(max_length=255)),
                ('customer_gst_type', models.CharField(max_length=50)),
                ('customer_gst_number', models.CharField(max_length=50)),
                ('customer_place_of_supply', models.CharField(max_length=50)),
                ('credit_note_date', models.DateField()),
                ('invoice_type', models.CharField(max_length=50)),
                ('invoice_number', models.CharField(max_length=50)),
                ('credit_note_number', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=50)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('upi_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='credit_notes/')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount_igst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('advanced_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_invoice')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 5)),
        ),
        migrations.CreateModel(
            name='Fin_CreditNote_Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_CreditNote_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Finsys_App.fin_creditnote')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_items')),
            ],
        ),
        migrations.CreateModel(
            name='Fin_CreditNote_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_creditnote')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
            ],
        ),
    ]
