# Generated by Django 4.2.4 on 2024-03-13 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0009_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_creditnote',
            name='company',
        ),
        migrations.RemoveField(
            model_name='fin_creditnote',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='fin_creditnote',
            name='login_details',
        ),
        migrations.AddField(
            model_name='fin_creditnote',
            name='LoginDetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details'),
        ),
        migrations.AddField(
            model_name='fin_creditnote',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details'),
        ),
        migrations.AddField(
            model_name='fin_creditnote',
            name='Customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_customers'),
        ),
    ]
