# Generated by Django 4.2.4 on 2024-03-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0010_remove_fin_creditnote_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_creditnote_history',
            old_name='company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_creditnote_history',
            old_name='login_details',
            new_name='LoginDetails',
        ),
        migrations.RenameField(
            model_name='fin_creditnote_reference',
            old_name='company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='fin_creditnote_reference',
            old_name='login_details',
            new_name='LoginDetails',
        ),
    ]
