# Generated by Django 4.2.4 on 2024-03-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0012_rename_bank_account_number_fin_creditnote_bank_acc_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_creditnote',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
