# Generated by Django 4.2.4 on 2024-03-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_rename_sub_total_fin_creditnote_subtotal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_creditnote_items',
            old_name='credit_note',
            new_name='CreditNote',
        ),
    ]
